flower_endpoint = "http://192.168.0.42"
recording_dir = "sample_recordings"
flower_interval = 30
yolo_verbose = false



[[cameras]]
uri = "192.168.0.3"

[[cameras]]
uri = "192.168.0.4"

[[cameras]]
uri = "192.168.0.5"
