[project]
name = "flower-power"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "joppe", email = "jboeve009@gmail.com" }
]
requires-python = ">=3.13"

dependencies = [
    "torch==2.11.0+cu126;	sys_platform == 'linux' and platform_machine == 'x86_64'",
	"torch==2.9.0;			sys_platform == 'darwin' or platform_machine == 'aarch64'",
    # "torchvision==0.26.0 ; sys_platform == 'linux' and platform_machine == 'aarch64'",
    "torchvision",
	# "torchvision ; sys_platform == 'darwin'",



    "msgspec>=0.21.1",
    "pillow>=12.2.0",
    "ultralytics>=8.4.51",
    "lap>=0.5.12",
    "httpx>=0.28.1",
]


[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
image-harvester = "image_harvester:harvester"
ping-test = "image_harvester:ping"
formula = "image_harvester:formula"
mock-controller = "mock_controller:main"


[tool.uv.build-backend]
# Say which top-level package you are shipping
module-name = "image_harvester"
# It lives at the project root (not under src/)
module-root = "src"
# namespace   = true


[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

